name: torch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - cudnn=7.6
  - ffmpeg
  - matplotlib
  - pillow
  - pip
  - python=3.8
  - scikit-image
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - pandas
  - numpy
  - tqdm
  - pip:
    - gputil


