
name: keras_env
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - cudnn=7.6
  - ffmpeg
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - python=3.8
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
      - tensorflow==2.3.0
      - gputil
